# Generated by Django 4.2.5 on 2023-11-03 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tropical', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='acc_type',
        ),
        migrations.RemoveField(
            model_name='account',
            name='branch',
        ),
    ]
